ARG GO_VERSION=latest
FROM golang:$GO_VERSION

WORKDIR /path/to/some/go

# TODO I wanted +fake on here but Go rejects the semver if it has +BUILD
ENV FAKEGIT_GO_SEMVER v1.2.3-4.5.6.7.8.9.0
ENV FAKEGIT_GO_REVISION 1.2.3.4.5.6.7.8.9.0
ENV FAKEGIT_GO_TIMESTAMP 1234567890

COPY fake-git.sh /usr/local/bin/git
RUN git --fake

# this could also be a file, but doing so needs new enough Go (https://github.com/golang/go/commit/d774ced6a97d3e354d92e874861fb24d7527e3cb) and the file to be a valid-looking "Git worktree" file pointing at a real directory somewhere else (https://github.com/golang/go/blob/d774ced6a97d3e354d92e874861fb24d7527e3cb/src/cmd/go/internal/vcs/vcs.go#L677-L698)
RUN mkdir -p .git

COPY test-go/ ./

RUN go build -buildvcs=true -o faked .
RUN set -eux; \
	go version -m ./faked | tee go-version.txt; \
	time="$(date --utc --date "@$FAKEGIT_GO_TIMESTAMP" '+%Y-%m-%dT%H:%M:%SZ')"; \
	{ \
		printf '%s\n' "$FAKEGIT_GO_SEMVER"; \
		printf 'vcs = "git"\n'; \
		printf 'vcs.revision = "%s"\n' "$FAKEGIT_GO_REVISION"; \
		printf 'vcs.time = "%s"\n' "$time"; \
		printf 'vcs.modified = "false"\n'; \
	} | tee expected.txt; \
	./faked | tee actual.txt; \
	diff -u expected.txt actual.txt; \
	tab="$(printf '\t')"; \
	for string in \
		"${tab}${FAKEGIT_GO_SEMVER}" \
		"${tab}vcs=git" \
		"${tab}vcs.revision=${FAKEGIT_GO_REVISION}" \
		"${tab}vcs.time=${time}" \
		"${tab}vcs.modified=false" \
	; do \
		grep -F "$string" go-version.txt; \
	done
